// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hagphxsersdskbagkuiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZ3BoeHNlcnNkc2tiYWdrdWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTcxODgsImV4cCI6MjA1OTg3MzE4OH0.tCv3mnl8vfvnw4fUV7z9QBVfPO1nJgc324jIKMqa3TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);